services:
  # Zookeeper service for Kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "${ZOOKEEPER_PORT}:2181"

  # Kafka service
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${KAFKA_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT}
    depends_on:
      - zookeeper

  # Kafka Manager for Kafka management
  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "${KAFKA_MANAGER_PORT}:9000"
    environment:
      ZK_HOSTS: zookeeper:${ZOOKEEPER_PORT}
    depends_on:
      - kafka
      - zookeeper

  # Couchbase service
  couchbase:
    image: couchbase:community-7.1.1
    ports:
      - "${COUCHBASE_ADMIN_PORT_1}:${COUCHBASE_ADMIN_PORT_1}" # Couchbase web console and services
      - "${COUCHBASE_ADMIN_PORT_2}:${COUCHBASE_ADMIN_PORT_2}"
      - "${COUCHBASE_DATA_PORT}:${COUCHBASE_DATA_PORT}"         # Data access port
    environment:
      COUCHBASE_ADMIN_USERNAME: "${COUCHBASE_ADMIN_USERNAME}"
      COUCHBASE_ADMIN_PASSWORD: "${COUCHBASE_ADMIN_PASSWORD}"

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms${ES_MEMORY} -Xmx${ES_MEMORY}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTICSEARCH_PORT_1}:9200"
      - "${ELASTICSEARCH_PORT_2}:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # Kibana for Elasticsearch management
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local
